DROP DATABASE IF EXISTS announcements;
CREATE DATABASE announcements;

DROP DATABASE IF EXISTS quotes;
CREATE DATABASE quotes;

DROP DATABASE IF EXISTS birthdays;
CREATE DATABASE birthdays;

DROP DATABASE IF EXISTS reminders;
CREATE DATABASE reminders;

DROP DATABASE IF EXISTS roles;
CREATE DATABASE roles;

DROP DATABASE IF EXISTS events;
CREATE DATABASE events;
